USE master
IF EXISTS (SELECT * FROM sys.databases WHERE name ='ApplicationDb')
DROP DATABASE ApplicationDb
CREATE DATABASE ApplicationDb

USE ApplicationDb

CREATE TABLE Venue (
	VenueID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	VenueName VARCHAR (250) NOT NULL,
	Location VARCHAR (250) NOT NULL,
	Capacity VARCHAR (250) NOT NULL,
	ImageURL VARCHAR (250) NOT NULL
)

CREATE TABLE Event (
	EventID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventName VARCHAR (250) NOT NULL,
	EventDate VARCHAR (250) NOT NULL,
	Description VARCHAR (250) NOT NULL
)

CREATE TABLE Booking (
	BookingID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventID INT,
	VenueID INT,
	BookingDate DATETIME,
	FOREIGN KEY (EventID) REFERENCES Event(EventID),
	FOREIGN KEY (VenueID) REFERENCES Venue(VenueID)
)

